=== SaschaDostal/Project_SaveData/DataDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Data (Settings, (Game|Series|Movie|Activity)*)>
    <!ELEMENT Settings (Name1, Name2, TextSize, SizeX, SizeY, Language)>
       <!ELEMENT Name1 (#PCDATA)>
       <!ELEMENT Name2 (#PCDATA)>
       <!ELEMENT TextSize (#PCDATA)>
       <!ELEMENT SizeX (#PCDATA)>
       <!ELEMENT SizeY (#PCDATA)>
       <!ELEMENT Language (#PCDATA)>
    <!ELEMENT Game (GName, GPlatform, GStatus)>
	   <!ELEMENT GName (#PCDATA)>
	   <!ELEMENT GPlatform (#PCDATA)>
	   <!ELEMENT GStatus (#PCDATA)>
    <!ELEMENT Series (SName, SPlatform, Seasons, SStatus)>
       <!ELEMENT SName (#PCDATA)>
       <!ELEMENT SPlatform (#PCDATA)>
	   <!ELEMENT Seasons (#PCDATA)>
	   <!ELEMENT SStatus (#PCDATA)>
	<!ELEMENT Movie (MName, Suggested, MStatus)>
       <!ELEMENT MName (#PCDATA)>
       <!ELEMENT Suggested (#PCDATA)>
       <!ELEMENT MStatus (#PCDATA)>
    <!ELEMENT Activity (Description, Location, Category, AStatus)>
       <!ELEMENT Description (#PCDATA)>
       <!ELEMENT Location (#PCDATA)>
       <!ELEMENT Category (#PCDATA)>
       <!ELEMENT AStatus (#PCDATA)>

=== SaschaDostal/Project_SaveData/Data_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Data SYSTEM "DataDTD.dtd">
<Data>
    <Settings>
        <Name1>Sascha</Name1>
        <Name2>Saskia</Name2>
        <TextSize>18</TextSize>
        <SizeX>896</SizeX>
        <SizeY>566</SizeY>
        <Language>de</Language>
    </Settings>
    <Game>
        <GName>Test</GName>
        <GPlatform>PC</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Game>
        <GName>Test1</GName>
        <GPlatform>PC_VR</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Game>
        <GName>Test2</GName>
        <GPlatform>Nintendo Switch</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Series>
        <SName>Test</SName>
        <SPlatform>BluRay</SPlatform>
        <Seasons>8</Seasons>
        <SStatus>Season 3</SStatus>
    </Series>
    <Series>
        <SName>Test1</SName>
        <SPlatform>DVD</SPlatform>
        <Seasons>9</Seasons>
        <SStatus>Season 1</SStatus>
    </Series>
    <Series>
        <SName>Test2</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>5+</Seasons>
        <SStatus>Season 2</SStatus>
    </Series>
    <Game>
        <GName>Test6</GName>
        <GPlatform>PC</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Series>
        <SName>13 Reasons Why</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>4</Seasons>
        <SStatus>Season 3</SStatus>
    </Series>
    <Game>
        <GName>Detroid: Become Human</GName>
        <GPlatform>PS4</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Series>
        <SName>TestSerie</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>8</Seasons>
        <SStatus>Finished</SStatus>
    </Series>
    <Activity>
        <Description>Test</Description>
        <Location>Home</Location>
        <Category>Sport</Category>
        <AStatus>Pending</AStatus>
    </Activity>
    <Movie>
        <MName>TestMovie</MName>
        <Suggested>Sascha</Suggested>
        <MStatus>Pending</MStatus>
    </Movie>
    <Series>
        <SName>Peter</SName>
        <SPlatform/>
        <Seasons/>
        <SStatus>Finished</SStatus>
    </Series>
    <Series>
        <SName/>
        <SPlatform/>
        <Seasons/>
        <SStatus/>
    </Series>
    <Activity>
        <Description>TestActivity</Description>
        <Location/>
        <Category/>
        <AStatus/>
    </Activity>
    <Activity>
        <Description>TestActivity1</Description>
        <Location/>
        <Category/>
        <AStatus>Pending</AStatus>
    </Activity>
    <Game>
        <GName>Testitest</GName>
        <GPlatform/>
        <GStatus/>
    </Game>
    <Game>
        <GName>Endgame</GName>
        <GPlatform>PS4</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Game>
        <GName>EA Games</GName>
        <GPlatform>PC</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Movie>
        <MName>Abba</MName>
        <Suggested>Sascha</Suggested>
        <MStatus>Pending</MStatus>
    </Movie>
    <Movie>
        <MName>Zeus</MName>
        <Suggested>Saskia</Suggested>
        <MStatus>Pending</MStatus>
    </Movie>
</Data>

=== SaschaDostal/Project_SaveData/Data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Data SYSTEM "DataDTD.dtd">
<Data>
    <Settings>
        <Name1>Sascha</Name1>
        <Name2/>
        <TextSize>18</TextSize>
        <SizeX>896</SizeX>
        <SizeY>566</SizeY>
        <Language>de</Language>
    </Settings>
    <Game>
        <GName>Test</GName>
        <GPlatform>PC</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Game>
        <GName>Test1</GName>
        <GPlatform>PC_VR</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Game>
        <GName>Test2</GName>
        <GPlatform>Nintendo Switch</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Series>
        <SName>Test</SName>
        <SPlatform>BluRay</SPlatform>
        <Seasons>8</Seasons>
        <SStatus>Season 3</SStatus>
    </Series>
    <Series>
        <SName>Test1</SName>
        <SPlatform>DVD</SPlatform>
        <Seasons>9</Seasons>
        <SStatus>Season 1</SStatus>
    </Series>
    <Series>
        <SName>Test2</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>5+</Seasons>
        <SStatus>Season 2</SStatus>
    </Series>
    <Game>
        <GName>Test6</GName>
        <GPlatform>PC</GPlatform>
        <GStatus>Pending</GStatus>
    </Game>
    <Series>
        <SName>13 Reasons Why</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>4</Seasons>
        <SStatus>Season 3</SStatus>
    </Series>
    <Game>
        <GName>Detroid: Become Human</GName>
        <GPlatform>PS4</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Movie>
        <MName>TestMovie</MName>
        <Suggested>Sascha</Suggested>
        <MStatus>Pending</MStatus>
    </Movie>
    <Movie>
        <MName>TestMovie2</MName>
        <Suggested>Saskia</Suggested>
        <MStatus>Finished</MStatus>
    </Movie>
    <Movie>
        <MName>TestMovie1</MName>
        <Suggested>Saskia</Suggested>
        <MStatus>Finished</MStatus>
    </Movie>
    <Activity>
        <Description>Walk in Park</Description>
        <Location>Outdoor</Location>
        <Category>Sport</Category>
        <AStatus>Pending</AStatus>
    </Activity>
    <Activity>
        <Description>Watch a movie</Description>
        <Location>Home</Location>
        <Category>Other</Category>
        <AStatus>Finished</AStatus>
    </Activity>
    <Movie>
        <MName>TestMovie3</MName>
        <Suggested>Sascha</Suggested>
        <MStatus>Finished</MStatus>
    </Movie>
    <Activity>
        <Description>TestActivity</Description>
        <Location>Outdoor</Location>
        <Category>Eating</Category>
        <AStatus>Pending</AStatus>
    </Activity>
    <Activity>
        <Description>TestActivity1</Description>
        <Location>Outside</Location>
        <Category>Eating</Category>
        <AStatus>Finished</AStatus>
    </Activity>
    <Activity>
        <Description>Whatever</Description>
        <Location>Outdoor</Location>
        <Category>Trip</Category>
        <AStatus>Pending</AStatus>
    </Activity>
    <Series>
        <SName>TestSerie</SName>
        <SPlatform>Netflix</SPlatform>
        <Seasons>8</Seasons>
        <SStatus>Finished</SStatus>
    </Series>
    <Activity>
        <Description>Test</Description>
        <Location>Home</Location>
        <Category>Sport</Category>
        <AStatus>Pending</AStatus>
    </Activity>
    <Game>
        <GName>TestGameForFile1</GName>
        <GPlatform>testitest</GPlatform>
        <GStatus>Finished</GStatus>
    </Game>
    <Game>
        <GName>Testgame</GName>
        <GPlatform/>
        <GStatus/>
    </Game>
    <Activity>
        <Description/>
        <Location/>
        <Category/>
        <AStatus/>
    </Activity>
    <Activity>
        <Description>123</Description>
        <Location/>
        <Category/>
        <AStatus/>
    </Activity>
    <Series>
        <SName>Testseries</SName>
        <SPlatform/>
        <Seasons/>
        <SStatus>Finished</SStatus>
    </Series>
    <Movie>
        <MName>TestMovie4</MName>
        <Suggested/>
        <MStatus>Pending</MStatus>
    </Movie>
    <Game>
        <GName>TestGame</GName>
        <GPlatform/>
        <GStatus/>
    </Game>
    <Movie>
        <MName>Abc</MName>
        <Suggested/>
        <MStatus>Finished</MStatus>
    </Movie>
</Data>
